# See https://pre-commit.com for more information
repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.29
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: end-of-file-fixer
# pytest
- repo: local
  hooks:
    - id: pytest
      name: Run pytest
      entry: uv run pytest
      language: system
      types: [python]
      stages: [pre-push]
