# 開発環境用の設定
version: '3.8'

services:
  fast-api:
    volumes:
      - ./backend/src:/app/src # コードの変更をリアルタイムに反映
    environment:
      - ENV=development # 開発環境で起動
      - DEBUG=True      # デバッグモードを有効化
  
  nextjs:
    volumes:
      - ./frontend/app:/app/app # コードの変更をリアルタイムに反映
      - node_modules:/app/node_modules # node_modulesを永続化することで、速度を向上
    environment:
      - NODE_ENV=development # 開発環境で起動
    command: ["npm", "run", "dev"] # 開発用のコマンドを実行

# ボリュームの定義
volumes:
  # node_modulesを永続化するためのボリューム
  node_modules:
